/**
 * Comprehensive Thai OCR Text Normalizer
 * Fixes floating vowels, displaced tone marks, broken diphthongs,
 * and unnatural intra-word whitespaces generated by Tesseract.js.
 */

// Thai Unicode ranges
const THAI_CONSONANTS = "[\\u0E01-\\u0E2E]";
const THAI_LEADING_VOWELS = "[\\u0E40-\\u0E44]"; // เ แ โ ใ ไ
const THAI_TRAILING_VOWELS = "[\\u0E30\\u0E32\\u0E33\\u0E45]"; // ะ า ำ ๅ
const THAI_UPPER_VOWELS = "[\\u0E31\\u0E34-\\u0E37\\u0E47]"; // ั ิ ี ึ ื ็
const THAI_LOWER_VOWELS = "[\\u0E38-\\u0E3A]"; // ุ ู ฺ
const THAI_TONE_MARKS = "[\\u0E48-\\u0E4C\\u0E4E]"; // ่ ้ ๊ ๋ ์ ๎
const THAI_NICHAHIT = "\\u0E4D"; // ํ
const THAI_ALL_MARKS = "[\\u0E31\\u0E34-\\u0E3A\\u0E47-\\u0E4E\\u0E4D]";

/**
 * Normalizes Thai text by fixing floating vowels and invalid mark ordering.
 */
export function normalizeThaiText(text: string): string {
  if (!text) return "";

  let result = text;

  // 1. Unicode Canonical Decomposition/Composition (NFC)
  result = result.normalize("NFC");

  // 2. Remove space between leading vowels (เ แ โ ใ ไ) and consonants
  // e.g. "เ ริ่ม" -> "เริ่ม", "โ ดย" -> "โดย"
  result = result.replace(new RegExp(`(${THAI_LEADING_VOWELS})\\s+(${THAI_CONSONANTS})`, "g"), "$1$2");

  // 3. Remove space between consonants and upper/lower vowels or tone marks (Floating vowels)
  // e.g. "ท ี่" -> "ที่", "ค ุณ" -> "คุณ"
  result = result.replace(new RegExp(`(${THAI_CONSONANTS})\\s+(${THAI_ALL_MARKS})`, "g"), "$1$2");

  // 3.1 Remove space between vowel-bearing consonant and its final consonant
  // e.g. "ดั น" -> "ดัน", "วั น" -> "วัน", "คิ ด" -> "คิด", "รุ่ น" -> "รุ่น"
  result = result.replace(
    new RegExp(
      `(${THAI_CONSONANTS}(?:${THAI_UPPER_VOWELS}|${THAI_LOWER_VOWELS})(?:${THAI_TONE_MARKS})?)\\s+(${THAI_CONSONANTS})`,
      "g"
    ),
    "$1$2"
  );

  // 4. Remove space between vowel and tone mark
  // e.g. "ที่ " or "ทิ ่" -> "ที่"
  result = result.replace(new RegExp(`(${THAI_UPPER_VOWELS}|${THAI_LOWER_VOWELS})\\s+(${THAI_TONE_MARKS})`, "g"), "$1$2");

  // 5. Remove space before trailing vowels (ะ า ำ ๅ)
  // e.g. "ม า" -> "มา", "จ ะ" -> "จะ", "ท ำ" -> "ทำ"
  result = result.replace(new RegExp(`(${THAI_CONSONANTS}(?:${THAI_TONE_MARKS})?)\\s+(${THAI_TRAILING_VOWELS})`, "g"), "$1$2");

  // 6. Fix inverted mark ordering: Tone mark before upper/lower vowel
  // Tesseract sometimes outputs [Consonant][Tone][Vowel] e.g. "ท่ี" instead of "ที่"
  result = result.replace(new RegExp(`(${THAI_TONE_MARKS})(${THAI_UPPER_VOWELS}|${THAI_LOWER_VOWELS})`, "g"), "$2$1");

  // 7. Fix Sara Am (ำ) decomposition and tone ordering
  // Nichahit (ํ) + Sara Aa (า) -> Sara Am (ำ)
  // [Tone] + ํ + า -> [Tone] + ำ
  // ํ + [Tone] + า -> [Tone] + ำ
  result = result.replace(new RegExp(`${THAI_NICHAHIT}\\s*(${THAI_TONE_MARKS})\\s*\\u0E32`, "g"), "$1\u0E33");
  result = result.replace(new RegExp(`(${THAI_TONE_MARKS})\\s*${THAI_NICHAHIT}\\s*\\u0E32`, "g"), "$1\u0E33");
  result = result.replace(new RegExp(`${THAI_NICHAHIT}\\s*\\u0E32`, "g"), "\u0E33");
  // Tone mark after Sara Am: ำ + [Tone] -> [Tone] + ำ
  result = result.replace(new RegExp(`\\u0E33(${THAI_TONE_MARKS})`, "g"), "$1\u0E33");

  // 8. Fix common cluster spaces created by OCR font kerning
  // e.g. "บ ริษัท" -> "บริษัท", "ป ระเทศ" -> "ประเทศ", "ส มัคร" -> "สมัคร", "ก รรม" -> "กรรม"
  result = result.replace(/([บปสคผตรพฟ])\s+([รลวนม])/g, "$1$2");

  // 9. Fix double spaces within Thai character sequences
  result = result.replace(/([\u0E00-\u0E7F])\s{2,}([\u0E00-\u0E7F])/g, "$1 $2");

  return result.trim();
}

/**
 * Returns true if a character or string contains Thai characters.
 */
export function isThai(str: string): boolean {
  return /[\u0E00-\u0E7F]/.test(str);
}
